from fpdf import FPDF
import datetime
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Quant AI Terminal | Institutional Research', 0, 1, 'R')
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 51, 102) # Navy Blue
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 8, body)
        self.ln()

    def add_metric_box(self, label, value):
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(240, 240, 240)
        self.cell(90, 10, f"{label}: {value}", 1, 0, 'L', 1)

def create_pdf(ticker, summary, analysis_text, filename="report.pdf"):
    try:
        pdf = PDFReport()
        pdf.add_page()
        
        # 1. Title
        pdf.set_font('Arial', 'B', 24)
        pdf.cell(0, 20, f"{ticker} Deep Dive Report", 0, 1, 'C')
        pdf.set_font('Arial', '', 12)
        pdf.cell(0, 10, f"Date: {datetime.date.today()}", 0, 1, 'C')
        pdf.ln(10)
        
        # 2. Key Metrics Summary
        if isinstance(summary, dict):
            pdf.chapter_title("1. Market Pulse (Key Metrics)")
            pdf.add_metric_box("Current Price", f"${summary.get('current_price', 0):.2f}")
            pdf.add_metric_box("RSI (14)", f"{summary.get('rsi', 0):.2f}")
            pdf.ln(10)
            pdf.add_metric_box("200-Day SMA", f"${summary.get('sma_200', 0):.2f}")
            pdf.add_metric_box("AI Signal", summary.get('sentiment', 'N/A'))
            pdf.ln(20)
        
        # 3. AI Analysis
        pdf.chapter_title("2. AI Technical Analysis")
        # 텍스트 깨짐 방지를 위해 latin-1 인코딩 가능한지 체크 (간단한 처리)
        clean_text = analysis_text.encode('latin-1', 'replace').decode('latin-1')
        pdf.chapter_body(clean_text)
        
        # 4. Disclaimer
        pdf.ln(20)
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.multi_cell(0, 5, "Disclaimer: This report is generated by Quant AI for informational purposes only.")
        
        # 파일 저장 (경로 문제 해결)
        pdf.output(filename)
        return filename
        
    except Exception as e:
        print(f"PDF Generation Error: {e}")
        return None